# Classification and Get 50 feature words

apply linearSVC or extract features that may be the characteristics of different author and then using those features along with the text releted features and train some classifier on it.


In [122]:
import pandas as pd
train=pd.read_csv(r"C:\Users\wangtao\Desktop\train_data600.csv",encoding='latin1')
y_train=train['author'].values
X_train=train['text'].values
test=pd.read_csv(r"C:\Users\wangtao\Desktop\test_data600.csv",encoding='latin1')
y_test=test['author'].values
X_test=test['text'].values

In [123]:
y_train.shape

(183,)

In [124]:
import numpy as np
training_labels = set(y_train)
print(training_labels)
#from scipy.stats import itemfreq
#test_category_dist = itemfreq(y_test)
#print(test_category_dist)
training_category_dist = np.unique(y_train)
print(training_category_dist)

{'RC', 'RY', 'JJ'}
['JJ' 'RC' 'RY']


In [133]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
## how to add in my own stopword list https://www.kaggle.com/c/msk-redefining-cancer-treatment/discussion/37679
from sklearn.feature_extraction import text 
## Add in stop words using  .union()
#stop_words_add = text.ENGLISH_STOP_WORDS.union(['mr','dr','martin','mary','jane','julia','lily',
#                                                'maria','jimmy','keran','dillion','mr fixit',
#                                               'mrs','mr browne','ll'])
## Using my own stop words list
stop_words_list = [x.strip() for x in open(r'C:\Users\wangtao\Desktop\stopwords.txt','r').read().split(',')]

bigram_tf = CountVectorizer(min_df=5, stop_words=list(stop_words_list),ngram_range=(1,2),encoding='latin1')
#bigram_tfidf = TfidfVectorizer(use_idf=True,min_df=5, stop_words=stop_words_add,ngram_range=(1,2),encoding='latin1')

In [134]:
# The vectorizer can do "fit" and "transform"
# fit is a process to collect unique tokens into the vocabulary
# transform is a process to convert each document to vector based on the vocabulary
# These two processes can be done together using fit_transform(), or used individually: fit() or transform()
X_train_vec = bigram_tf.fit_transform(X_train)
#X_train_tfidfvec = bigram_tfidf.fit_transform(X_train)

In [135]:
from sklearn.svm import LinearSVC
svm_clf = LinearSVC(C=1)
svm_clf.fit(X_train_vec,y_train)
#svm_clf.fit(X_train_tfidfvec,y_train)

LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [144]:
feature_rank1= sorted(zip(svm_clf.coef_[1],bigram_tf.get_feature_names()))
a1=feature_rank1[-50:]
for i in range(0,50):
    print(a1[i])


(0.009246137073142374, 'kid')
(0.009276751221242137, 'fish')
(0.009289666115604184, 'house')
(0.009375497420700783, 'just')
(0.009452868009980301, 'those')
(0.009548443288428665, 'put')
(0.009552245319160171, 'call')
(0.009564533884326218, 'around')
(0.00957864487722762, 'goes')
(0.009845073486779526, 'woman')
(0.010113571129814957, 'they')
(0.010220464496758268, 'say')
(0.010435947584806574, 'started')
(0.010476349170415834, 'days')
(0.010636885724064557, 'window')
(0.010945684644954273, 'can')
(0.011160826858023972, 'bass')
(0.011662127746033962, 'guard')
(0.011965591288398386, 'newspaper')
(0.011966500264698482, 'things')
(0.012180406919146996, 'said')
(0.01219156165688178, 'went')
(0.012226440365205152, 'into')
(0.01228881509106607, 'took')
(0.012353564493055474, 'laura said')
(0.01251753778243383, 'seen')
(0.013559955981632232, 'kitchen')
(0.013574907291347625, 'go')
(0.014233597758035028, 'glass')
(0.01429076639612783, 'says')
(0.01454113144914347, 'she')
(0.014650119140923847, '

## Get 50 feature words 

In [143]:
feature_rank = sorted(zip(svm_clf.coef_[0],bigram_tf.get_feature_names()))
feature_rank1= sorted(zip(svm_clf.coef_[1],bigram_tf.get_feature_names()))
feature_rank2 = sorted(zip(svm_clf.coef_[2],bigram_tf.get_feature_names()))

a=feature_rank[-50:]
a1=feature_rank1[-50:]
a2=feature_rank2[-50:]
l=[]
l1=[]
l2=[]
for i in range(0,50):
    print(a2[i])
    l.append(a[i])
    l1.append(a1[i])
    l2.append(a2[i])
f_data = {'James Joyce':l,'Raymond Carver':l1,'Richard Yates':l2}

df_f_data=pd.DataFrame(f_data)

with open (r'C:\Users\wangtao\Desktop\featurewords.csv','w')as f:
    df_f_data.to_csv(f)


# This is a function I found from stackexchange, and adapted a little bit
# The purpose is to print the top and bottom features nicely
# https://stackoverflow.com/questions/11116697/how-to-get-most-informative-features-for-scikit-learn-classifiers

# You can find many useful scripts from stackexchange or GitHub
# Most tasks are not so unique, so someone in this world might have done something similar and shared their code

#def show_most_and_least_informative_features(vectorizer, clf, class_idx=0, n=10):
#    feature_names = vectorizer.get_feature_names()
#    coefs_with_fns = sorted(zip(clf.feature_log_prob_[class_idx], feature_names))
#    top = zip(coefs_with_fns[:n], coefs_with_fns[-n:])
#    for (coef_2, fn_2) in top:
#        print("\t%.4f\t%-15s" %  coef_2, fn_2)
    
#print()

(0.011890557393890265, 'siz')
(0.012029472033609764, 'only')
(0.012084983202090586, 'and it')
(0.012231005941709033, 'with')
(0.012344289396942147, 'lieutenant')
(0.012562950566623007, 'to be')
(0.012651058173018816, 'home')
(0.012809966897619336, 'make')
(0.013046631836051276, 'goodnight')
(0.013107229832908684, 'well')
(0.013112030440465933, 'made')
(0.013728042391494229, 'gave')
(0.013859966174601931, 'of his')
(0.014175951067184781, 'right')
(0.014184862953402617, 'she said')
(0.014235529115146188, 'look')
(0.014284473822670436, 'yew')
(0.014318708021017638, 'guess')
(0.014322662361528408, 'week')
(0.014598489101945392, 'job')
(0.014602115445200728, 'smile')
(0.014716079870364288, 'lips')
(0.014807541833814383, 'wasn')
(0.014864536138521414, 'time')
(0.015501923091837694, 'half')
(0.015593993874242184, 'ralph')
(0.015659843719690186, 'don')
(0.01586362939340596, 'off')
(0.016953345030889303, 'anyway')
(0.017175327552721668, 'ya')
(0.01749620882990279, 'got')
(0.01808896373076504, '

## How about the scores that indicate the performance of the model

In [137]:
X_test_vec = bigram_tf.transform(X_test)

In [138]:
svm_clf.score(X_test_vec,y_test)

0.975609756097561

if making one sentece per dobument the score is 0.5486404833836858
and score is much higher when change the size of each dobuments and the number of documents!!

In [139]:
from sklearn.metrics import confusion_matrix
y_pred = svm_clf.predict(X_test_vec)
cm = confusion_matrix(y_test,y_pred,labels=['JJ','RY','RC'])
print(cm)

from sklearn.metrics import classification_report
target_names = ['JJ','RY','RC']
print(classification_report(y_test,y_pred,target_names=target_names))

[[15  0  0]
 [ 0 15  1]
 [ 0  0 10]]
             precision    recall  f1-score   support

         JJ       1.00      1.00      1.00        15
         RY       0.91      1.00      0.95        10
         RC       1.00      0.94      0.97        16

avg / total       0.98      0.98      0.98        41



In [142]:
# print out specific type of error for further analysis

# print out the very positive examples that are mistakenly predicted as negative
# according to the confusion matrix, there should be 53 such examples
# note if you use a different vectorizer option, your result might be different

err_cnt = 0
for i in range(0, len(y_test)):
    if(y_test[i]=='RY' and y_pred[i]=='RC'):
        print(X_test[i])
        print(i)
        err_cnt = err_cnt+1
print("errors:", err_cnt)

fun with a stranger can you?" She gave them a homely shy smile. And that's just the way it is with words. When she said something like that it was more embarrassing than anything else but it did leave the children with a certain vague sense of responsibility toward her and often prompted them into a loyal reticence when children from other classes demanded to know how bad she really was. Well not too bad they would say uncomfortably and try to change the subject. John Gerhardt and Howard White usually walked home from school together and often as not though they tried to avoid it they were joined by two of the children from Mrs.Cleary's class who lived on their street Freddy Taylor and his twin sister Grace. John and Howard usually got about as far as the end of the playground before the twins came running after them out of the crowd. Hey wait up! Freddy would call. Wait up! And in a moment the twins would fall into step beside them chattering swinging their identical plaid canvas scho

In [47]:
#X_test_tfidfvec = bigram_tfidf.transform(X_test)

In [21]:
#svm_clf.score(X_test_tfidfvec,y_test)

0.8663490471414242

In [23]:
#from sklearn.metrics import confusion_matrix
#y_pred = svm_clf.predict(X_test_tfidfvec)
#cm = confusion_matrix(y_test,y_pred,labels=['JJ','RY','RC'])
#print(cm)

#from sklearn.metrics import classification_report
#target_names = ['JJ','RY','RC']
#print(classification_report(y_test,y_pred,target_names=target_names))

[[2573  107  254]
 [ 113 2186  287]
 [ 153  152 2151]]
             precision    recall  f1-score   support

         JJ       0.91      0.88      0.89      2934
         RY       0.80      0.88      0.84      2456
         RC       0.89      0.85      0.87      2586

avg / total       0.87      0.87      0.87      7976

